function [adigatorFunInfo, adigatorOutputs] = adigatortempfunc4(adigatorFunInfo,adigatorInputs)
[flag, adigatorFunInfo, adigatorInputs] = adigatorFunctionInitialize(4,adigatorFunInfo,adigatorInputs);
if flag; adigatorOutputs = adigatorInputs; return; end;
t = adigatorInputs{1};
X = adigatorInputs{2};
solution = adigatorInputs{3};
nargin = 3; nargout = 1;adigatorVarAnalyzer('% model constants');
m = 4.5;
m = adigatorVarAnalyzer('m = 4.5;',m,'m',0);
rho = 1.225;
rho = adigatorVarAnalyzer('rho = 1.225;',rho,'rho',0);
S = 0.473;
S = adigatorVarAnalyzer('S = 0.473;',S,'S',0);
g = 9.806;
g = adigatorVarAnalyzer('g = 9.806;',g,'g',0);
Cd0 = 0.0173;
Cd0 = adigatorVarAnalyzer('Cd0 = 0.0173;',Cd0,'Cd0',0);
Cd1 = -0.0337;
Cd1 = adigatorVarAnalyzer('Cd1 = -0.0337;',Cd1,'Cd1',0);
Cd2 = 0.0517;
Cd2 = adigatorVarAnalyzer('Cd2 = 0.0517;',Cd2,'Cd2',0);
VR = solution.VR;
VR = adigatorVarAnalyzer('VR = solution.VR;',VR,'VR',0);
tf = solution.tf;
tf = adigatorVarAnalyzer('tf = solution.tf;',tf,'tf',0);
coeffs = solution.coeffs;
coeffs = adigatorVarAnalyzer('coeffs = solution.coeffs;',coeffs,'coeffs',0);
N = solution.N;
N = adigatorVarAnalyzer('N = solution.N;',N,'N',0);
V = X(1,1);
V = adigatorVarAnalyzer('V = X(1,1);',V,'V',0);
gamma = X(3,1);
gamma = adigatorVarAnalyzer('gamma = X(3,1);',gamma,'gamma',0);
chi = X(2,1);
chi = adigatorVarAnalyzer('chi = X(2,1);',chi,'chi',0);
z = X(6,1);
z = adigatorVarAnalyzer('z = X(6,1);',z,'z',0);
adigatorVarAnalyzer('% get control inputs from time history');
% Call to User Function get_traj --- (FunID 5)
cadainput5_1 = t;
cadainput5_1 = adigatorVarAnalyzer('cadainput5_1 = t;',cadainput5_1,'cadainput5_1',0);
cadainput5_2 = tf;
cadainput5_2 = adigatorVarAnalyzer('cadainput5_2 = tf;',cadainput5_2,'cadainput5_2',0);
cadainput5_3 = coeffs;
cadainput5_3 = adigatorVarAnalyzer('cadainput5_3 = coeffs;',cadainput5_3,'cadainput5_3',0);
cadainput5_4 = N;
cadainput5_4 = adigatorVarAnalyzer('cadainput5_4 = N;',cadainput5_4,'cadainput5_4',0);
adigatorInputs = {cadainput5_1;cadainput5_2;cadainput5_3;cadainput5_4};
[adigatorFunInfo, adigatorOutputs] = adigatortempfunc5(adigatorFunInfo,adigatorInputs);
cadaoutput5_1 = adigatorOutputs{1};
sigma = cadaoutput5_1;
sigma = adigatorVarAnalyzer('sigma = cadaoutput5_1;',sigma,'sigma',0);
% Call to User Function get_xu --- (FunID 3)
cadainput3_1 = sigma;
cadainput3_1 = adigatorVarAnalyzer('cadainput3_1 = sigma;',cadainput3_1,'cadainput3_1',0);
cadainput3_2 = VR;
cadainput3_2 = adigatorVarAnalyzer('cadainput3_2 = VR;',cadainput3_2,'cadainput3_2',0);
adigatorInputs = {cadainput3_1;cadainput3_2};
[adigatorFunInfo, adigatorOutputs] = adigatortempfunc3(adigatorFunInfo,adigatorInputs);
cadaoutput3_1 = adigatorOutputs{1};
cadaoutput3_2 = adigatorOutputs{2};
u = cadaoutput3_2;
u = adigatorVarAnalyzer('u = cadaoutput3_2;',u,'u',0);
Cl = u(1);
Cl = adigatorVarAnalyzer('Cl = u(1);',Cl,'Cl',0);
nu = u(2);
nu = adigatorVarAnalyzer('nu = u(2);',nu,'nu',0);
CT = u(3);
CT = adigatorVarAnalyzer('CT = u(3);',CT,'CT',0);
Cd = Cd0 + Cd1*Cl + Cd2*Cl^2;
Cd = adigatorVarAnalyzer('Cd = Cd0 + Cd1*Cl + Cd2*Cl^2;',Cd,'Cd',0);
D = 0.5*rho*S*V^2*Cd;
D = adigatorVarAnalyzer('D = 0.5*rho*S*V^2*Cd;',D,'D',0);
L = 0.5*rho*S*V^2*Cl;
L = adigatorVarAnalyzer('L = 0.5*rho*S*V^2*Cl;',L,'L',0);
T = 0.5*rho*S*V^2*CT;
T = adigatorVarAnalyzer('T = 0.5*rho*S*V^2*CT;',T,'T',0);
adigatorVarAnalyzer('% wind model');
p_exp = 1;
p_exp = adigatorVarAnalyzer('p_exp = 1;',p_exp,'p_exp',0);
Wx = VR*(-z)^p_exp;
Wx = adigatorVarAnalyzer('Wx = VR*(-z)^p_exp;',Wx,'Wx',0);
Wxz = (p_exp*VR)*((-z)^p_exp)/z;
Wxz = adigatorVarAnalyzer('Wxz = (p_exp*VR)*((-z)^p_exp)/z;',Wxz,'Wxz',0);
zdot = -V*sin(gamma);
zdot = adigatorVarAnalyzer('zdot = -V*sin(gamma);',zdot,'zdot',0);
xdot = V*cos(chi)*cos(gamma) + Wx;
xdot = adigatorVarAnalyzer('xdot = V*cos(chi)*cos(gamma) + Wx;',xdot,'xdot',0);
ydot = V*sin(chi)*cos(gamma);
ydot = adigatorVarAnalyzer('ydot = V*sin(chi)*cos(gamma);',ydot,'ydot',0);
Vdot = (-D/m) - g*sin(gamma) - Wxz*zdot*cos(chi)*cos(gamma) + (T/m);
Vdot = adigatorVarAnalyzer('Vdot = (-D/m) - g*sin(gamma) - Wxz*zdot*cos(chi)*cos(gamma) + (T/m);',Vdot,'Vdot',0);
chidot = (L*sin(nu)/(m*V*cos(gamma))) + Wxz*zdot*sin(chi)/(V*cos(gamma));
chidot = adigatorVarAnalyzer('chidot = (L*sin(nu)/(m*V*cos(gamma))) + Wxz*zdot*sin(chi)/(V*cos(gamma));',chidot,'chidot',0);
gammadot = (L*cos(nu)/(m*V)) - g*cos(gamma)/V + Wxz*zdot*cos(chi)*sin(gamma)/V;
gammadot = adigatorVarAnalyzer('gammadot = (L*cos(nu)/(m*V)) - g*cos(gamma)/V + Wxz*zdot*cos(chi)*sin(gamma)/V;',gammadot,'gammadot',0);
ydot = [Vdot; chidot; gammadot; xdot; ydot; zdot];
ydot = adigatorVarAnalyzer('ydot = [Vdot; chidot; gammadot; xdot; ydot; zdot];',ydot,'ydot',0);
adigatorOutputs = {ydot};
[adigatorFunInfo, adigatorOutputs] = adigatorFunctionEnd(4,adigatorFunInfo,adigatorOutputs);
